//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : MetaMask Unity SDK ABI Code Generator
//   Input filename:  Playspace.sol
//   Output filename: Playspace.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------

using System;
using System.Numerics;
using System.Threading.Tasks;
using evm.net;
using evm.net.Models;

namespace Playspace
{
	#if UNITY_EDITOR || !ENABLE_MONO
	[BackedType(typeof(PlayspaceBacking))]
	#endif
	public interface Playspace : IContract
	{
		[EvmMethodInfo(Name = "addplayer", View = false)]
		Task<Transaction> Addplayer(EvmAddress userAddress, String name, CallOptions options = default);
		
		[EvmMethodInfo(Name = "sendBalance", View = false)]
		Task<Transaction> SendBalance(EvmAddress userAddress, BigInteger balanceToAdd, CallOptions options = default);
		
		[EvmMethodInfo(Name = "setScore", View = false)]
		Task<Transaction> SetScore(EvmAddress userAddress, BigInteger score, CallOptions options = default);
		
		[EvmConstructorMethod]
		Task<Playspace> DeployNew();
		
		[EvmMethodInfo(Name = "getPlayer", View = true)]
		Task<String> GetPlayer(EvmAddress userAddress, CallOptions options = default);
		
		[EvmMethodInfo(Name = "getScore", View = true)]
		Task<BigInteger> GetScore(EvmAddress userAddress, CallOptions options = default);
		
	}
}
