//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : MetaMask Unity SDK ABI Code Generator
//   Input filename:  Froggy.sol
//   Output filename: Froggy.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------

using System;
using System.Numerics;
using System.Threading.Tasks;
using evm.net;
using evm.net.Models;

namespace Froggy
{
	#if UNITY_EDITOR || !ENABLE_MONO
	[BackedType(typeof(FroggyBacking))]
	#endif
	public interface Froggy : IContract
	{
		[EvmMethodInfo(Name = "burnShot", View = false)]
		Task<Transaction> BurnShot(EvmAddress _playerAddress, CallOptions options = default);
		
		[EvmMethodInfo(Name = "checkPot", View = false)]
		Task<Transaction> CheckPot();
		
		[EvmMethodInfo(Name = "entranceFeeAmount", View = false)]
		Task<Transaction> EntranceFeeAmount(BigInteger newEntranceFee, CallOptions options = default);
		
		[EvmMethodInfo(Name = "payEntranceFee", View = false)]
		Task<Transaction> PayEntranceFee(EvmAddress senderr, CallOptions options = default);
		
		[EvmMethodInfo(Name = "prizeDistributer", View = false)]
		Task<Transaction> PrizeDistributer();
		
		[EvmMethodInfo(Name = "setScore", View = false)]
		Task<Transaction> SetScore(BigInteger score, CallOptions options = default);
		
		[EvmMethodInfo(Name = "transferOwnership", View = false)]
		Task<Transaction> TransferOwnership(EvmAddress newOwner, CallOptions options = default);
		
		[EvmConstructorMethod]
		Task<Froggy> DeployNew();
		
		[EvmMethodInfo(Name = "getHighfirstdadd", View = true)]
		Task<EvmAddress> GetHighfirstdadd();
		
		[EvmMethodInfo(Name = "getHighFirstScore", View = true)]
		Task<BigInteger> GetHighFirstScore();
		
		[EvmMethodInfo(Name = "getHighseconddadd", View = true)]
		Task<EvmAddress> GetHighseconddadd();
		
		[EvmMethodInfo(Name = "getHighsecondScore", View = true)]
		Task<BigInteger> GetHighsecondScore();
		
		[EvmMethodInfo(Name = "getHightest", View = true, Returns = new[] {"uint256","uint256","uint256","address","address","address"})]
		[return: EvmParameterInfo(Type = "tuple")]
		Task<Tuple<BigInteger, BigInteger, BigInteger, EvmAddress, EvmAddress, EvmAddress>> GetHightest();
		
		[EvmMethodInfo(Name = "getHighthirdadd", View = true)]
		Task<EvmAddress> GetHighthirdadd();
		
		[EvmMethodInfo(Name = "getHighthirdScore", View = true)]
		Task<BigInteger> GetHighthirdScore();
		
		[EvmMethodInfo(Name = "getPlayerScore", View = true)]
		Task<BigInteger> GetPlayerScore(EvmAddress _playerAddress, CallOptions options = default);
		
		[EvmMethodInfo(Name = "getPlayerShots", View = true)]
		Task<BigInteger> GetPlayerShots(EvmAddress _playerAddress, CallOptions options = default);
		
		[EvmMethodInfo(Name = "getPotSetTime", View = true)]
		Task<BigInteger> GetPotSetTime();
		
		[EvmMethodInfo(Name = "getPubBalance", View = true)]
		Task<BigInteger> GetPubBalance();
		
		[EvmMethodInfo(Name = "getPubState", View = true, Returns = new[] {"uint256","uint256"})]
		[return: EvmParameterInfo(Type = "tuple")]
		Task<Tuple<BigInteger, BigInteger>> GetPubState();
		
		[EvmMethodInfo(Name = "getTotalStokenBalance", View = true)]
		Task<BigInteger> GetTotalStokenBalance();
		
	}
}
